# Generated by Django 3.2.5 on 2021-08-01 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20210801_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.RemoveField(
            model_name='teckstack',
            name='news_img',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teckstack',
            name='img',
            field=models.FileField(null=True, upload_to='static/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'svg'])]),
        ),
    ]
