# Generated by Django 3.2.5 on 2021-08-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20210801_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='teckstack',
            name='len_stack',
            field=models.IntegerField(default=0),
        ),
    ]
