# Generated by Django 3.2.5 on 2021-08-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20210802_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
