# Generated by Django 3.2.5 on 2021-08-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_formmodel_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormModel',
        ),
    ]
