# Generated by Django 3.2.5 on 2021-08-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_delete_formmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
