# Generated by Django 3.2.5 on 2021-08-05 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20210805_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teckstack',
            name='img',
            field=models.FileField(null=True, upload_to='static/images', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'svg'])]),
        ),
    ]
